spring.application.name=bookstore

# H2 Database configuration - Development
spring.datasource.url=jdbc:h2:mem:bookstoredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate ddl-auto (update or create-drop is good for in-memory)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Properties
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# Server Configuration
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.bookstore=DEBUG
logging.level.org.springframework.security=DEBUG
